### PR TITLE
Mvdb/setup v2 api

### PR DESCRIPTION
**Pull request by m-vdb**

### CODE REVIEW

**Comment by m-vdb** [comment]
hey @motymichaely I did a bunch of work to work with v2 API. Also, I've written some tests. To run them, you just need to `python setup.py test`. Can you include them in your CI tool? LMK if I can do more ^^

**Comment by motymichaely** [comment]
@m-vdb - Looks good. 

We have plans on starting to work on an official v2 sdk for Python.

**Comment by m-vdb** [comment]
nice :)

**Comment by m-vdb** [comment]
thanks!

**Pull request merged**
